server:
  port: 8088
spring:
  thymeleaf:
    cache: false
  # 配置国际化
  messages:
    basename: i18n.login
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://124.222.244.117:3306/zrgj2?useUnicode=true&characterEncoding=utf8
      username: zrgj2
      password: zrgj2

mybatis-plus:
  type-aliases-package:
  mapper-locations:
  global-config:
    db-config:
      id-type: auto

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
